AWSTemplateFormatVersion: 2010-09-09

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ParamLambdaSecret:
    Description: The secret password for the Lambda Function
    Default: Test123
    Type: String

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./api.yml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref LambdaFunction

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../target/lambda.jar
      Handler: de.networkchallenge.lambda.ddns.MainHandler
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          DDNS_SECRET: !Ref ParamLambdaSecret
      Policies:
        Statement:
          - Resource: arn:aws:route53:::hostedzone/*
            Effect: Allow
            Action:
              - route53:ListResourceRecordSets
              - route53:ChangeResourceRecordSets
          - Resource: '*'
            Effect: Allow
            Action:
              - route53:ListHostedZones
      Events:
        ProxyEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY

  LambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*
  DnsZoneNC:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: NC root ddns zone
      Name: ddns.networkchallenge.de

Outputs:
  ApiGatewayUri:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Stage/"


